# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/low_contrast_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(870, 575)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.before_img_lbl = QtWidgets.QLabel(self.frame_3)
        self.before_img_lbl.setMaximumSize(QtCore.QSize(450, 700))
        self.before_img_lbl.setScaledContents(True)
        self.before_img_lbl.setObjectName("before_img_lbl")
        self.horizontalLayout.addWidget(self.before_img_lbl, 0, QtCore.Qt.AlignTop)
        self.frame5 = QtWidgets.QFrame(self.frame_3)
        self.frame5.setMaximumSize(QtCore.QSize(450, 700))
        self.frame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame5.setObjectName("frame5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.before_plt_layout = QtWidgets.QVBoxLayout()
        self.before_plt_layout.setObjectName("before_plt_layout")
        self.verticalLayout_5.addLayout(self.before_plt_layout)
        self.horizontalLayout.addWidget(self.frame5, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("QPushButton,QComboBox{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(34, 34, 34, 34);\n"
"    border: 0px solid; \n"
"}\n"
"QPushButton:hover,QComboBox:hover{\n"
"    background-color: rgb(230,4,64);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.operation_com = QtWidgets.QComboBox(self.frame)
        self.operation_com.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.operation_com.setFont(font)
        self.operation_com.setObjectName("operation_com")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.verticalLayout.addWidget(self.operation_com)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.choose_image_btn = QtWidgets.QPushButton(self.frame)
        self.choose_image_btn.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.choose_image_btn.setFont(font)
        self.choose_image_btn.setObjectName("choose_image_btn")
        self.horizontalLayout_3.addWidget(self.choose_image_btn)
        self.do_btn = QtWidgets.QPushButton(self.frame)
        self.do_btn.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.do_btn.setFont(font)
        self.do_btn.setObjectName("do_btn")
        self.horizontalLayout_3.addWidget(self.do_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.frame, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_4.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.after_layout = QtWidgets.QHBoxLayout()
        self.after_layout.setObjectName("after_layout")
        self.after_img_lbl = QtWidgets.QLabel(Form)
        self.after_img_lbl.setMaximumSize(QtCore.QSize(450, 700))
        self.after_img_lbl.setScaledContents(True)
        self.after_img_lbl.setObjectName("after_img_lbl")
        self.after_layout.addWidget(self.after_img_lbl)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setMaximumSize(QtCore.QSize(450, 700))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.after_plt_layout = QtWidgets.QVBoxLayout()
        self.after_plt_layout.setSpacing(0)
        self.after_plt_layout.setObjectName("after_plt_layout")
        self.verticalLayout_6.addLayout(self.after_plt_layout)
        self.after_layout.addWidget(self.frame_4)
        self.verticalLayout_3.addLayout(self.after_layout)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setStyleSheet("QPushButton,QComboBox{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(34, 34, 34, 34);\n"
"    border: 0px solid; \n"
"}\n"
"QPushButton:hover,QComboBox:hover{\n"
"    background-color: rgb(230,4,64);\n"
"}\n"
"QLineEdit{\n"
"background-color:rgb(255, 255, 255);\n"
"    color: rgb(230,4,64);\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMaximumSize(QtCore.QSize(55555, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tools_layout = QtWidgets.QVBoxLayout()
        self.tools_layout.setObjectName("tools_layout")
        self.verticalLayout_9.addLayout(self.tools_layout)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.go_btn = QtWidgets.QPushButton(self.frame_2)
        self.go_btn.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.go_btn.setFont(font)
        self.go_btn.setObjectName("go_btn")
        self.verticalLayout_2.addWidget(self.go_btn)
        self.verticalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_3.setStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.before_img_lbl.setText(_translate("Form", "Image before effect will display here"))
        self.operation_com.setItemText(0, _translate("Form", "Look-up table"))
        self.operation_com.setItemText(1, _translate("Form", "Histogram Stretching"))
        self.operation_com.setItemText(2, _translate("Form", "Histogram Equalization"))
        self.choose_image_btn.setText(_translate("Form", "Select Image"))
        self.do_btn.setText(_translate("Form", "DO"))
        self.after_img_lbl.setText(_translate("Form", "Image after effect will display here"))
        self.go_btn.setText(_translate("Form", "GO"))
