# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/noisy_image_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1021, 574)
        Form.setStyleSheet("QPushButton,QComboBox{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(34, 34, 34, 34);\n"
"    border: 0px solid; \n"
"}\n"
"QPushButton:hover,QComboBox:hover{\n"
"    background-color: rgb(230,4,64);\n"
"}\n"
"")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_before_lbl = QtWidgets.QLabel(Form)
        self.image_before_lbl.setMaximumSize(QtCore.QSize(700, 700))
        self.image_before_lbl.setScaledContents(True)
        self.image_before_lbl.setObjectName("image_before_lbl")
        self.verticalLayout_2.addWidget(self.image_before_lbl)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("QPushButton,QComboBox{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(34, 34, 34, 34);\n"
"    border: 0px solid; \n"
"}\n"
"QPushButton:hover,QComboBox:hover{\n"
"    background-color: rgb(230,4,64);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.operation_com = QtWidgets.QComboBox(self.frame)
        self.operation_com.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.operation_com.setFont(font)
        self.operation_com.setObjectName("operation_com")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.operation_com.addItem("")
        self.verticalLayout.addWidget(self.operation_com)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.mask_size_line = QtWidgets.QLineEdit(self.frame)
        self.mask_size_line.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mask_size_line.setFont(font)
        self.mask_size_line.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.mask_size_line.setText("")
        self.mask_size_line.setObjectName("mask_size_line")
        self.horizontalLayout_3.addWidget(self.mask_size_line)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.choose_image_btn = QtWidgets.QPushButton(self.frame)
        self.choose_image_btn.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choose_image_btn.setFont(font)
        self.choose_image_btn.setObjectName("choose_image_btn")
        self.horizontalLayout_2.addWidget(self.choose_image_btn)
        self.go_btn = QtWidgets.QPushButton(self.frame)
        self.go_btn.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.go_btn.setFont(font)
        self.go_btn.setObjectName("go_btn")
        self.horizontalLayout_2.addWidget(self.go_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.image_after_lbl = QtWidgets.QLabel(Form)
        self.image_after_lbl.setMaximumSize(QtCore.QSize(700, 700))
        self.image_after_lbl.setScaledContents(True)
        self.image_after_lbl.setObjectName("image_after_lbl")
        self.verticalLayout_4.addWidget(self.image_after_lbl)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4.addWidget(self.frame_2, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.image_before_lbl.setText(_translate("Form", "Image before effect will display here"))
        self.operation_com.setItemText(0, _translate("Form", "Neighbourhood operation Min Filter"))
        self.operation_com.setItemText(1, _translate("Form", "Neighbourhood operation Max Filter"))
        self.operation_com.setItemText(2, _translate("Form", "Neighbourhood operation Mean Filter"))
        self.operation_com.setItemText(3, _translate("Form", "Neighbourhood operation Median Filter"))
        self.operation_com.setItemText(4, _translate("Form", "Smoothing Average operation"))
        self.operation_com.setItemText(5, _translate("Form", "Smoothing Weighted Average operation"))
        self.operation_com.setItemText(6, _translate("Form", "Smoothing median filtering"))
        self.operation_com.setItemText(7, _translate("Form", "laplacian filter"))
        self.operation_com.setItemText(8, _translate("Form", "outlier method"))
        self.operation_com.setItemText(9, _translate("Form", "image averaging"))
        self.operation_com.setItemText(10, _translate("Form", "Adaptive"))
        self.operation_com.setItemText(11, _translate("Form", "notch filter"))
        self.label_2.setText(_translate("Form", "Set Mask Size"))
        self.choose_image_btn.setText(_translate("Form", "Select Image"))
        self.go_btn.setText(_translate("Form", "Go"))
        self.image_after_lbl.setText(_translate("Form", "TextLabel"))
