from view_manager.image_processing_manager import  ImageApp
from view_manager.arithmetic_operations import PointOperations
from view_manager.two_image_process import TowImage
from view_manager.low_contrast_image import LowContrast
from view_manager.noisy_image_manager import NosiyImage